### ISSUE TITLE
Game crash on startup when having Phantasm installed with Unusual Ends

### ISSUE THREAD

**Issue by cal1407** [Lyof429/EndsPhantasm#18]
Crash on startup with exit code 1.

Latest log: https://pastebin.com/cr5qrGDu

**Comment by Sweetygamer2** [comment]
Will take a look at it when i'm available

**Comment by Sweetygamer2** [comment]
Do you have the crash log ? Cuz this seems relatively normal tbh

**Comment by cal1407** [comment]
No unfortunately. Its an exit code 1 crash so no crash logs are generated

**Comment by Sweetygamer2** [comment]
Yeah the issue is between Unusual End and other launchers than Forge, will try to look for potential fixs when i get back from work

**Comment by Sweetygamer2** [comment]
Okay could you try some stuff for me ? I think the more exact issue it between Unusual End, End's Phantasm and Fabric API since they all have an End Biome mixin. Could you try with Unusual End alone, UE and Phantasm and UE and Sinytra ? Else i'll try later today

**Comment by cal1407** [comment]
Sorry for the late reply. I can confirm that the game loads just fine if only running UE and Phantasm, while it crashes if I have Connector installed

**Comment by Sweetygamer2** [comment]
Yeah we discussed it in intern with multiple devs, sinytra can only work with a single End mod at the time making UE, EP and EB cross-incompatible when Sinytra is used (so with sinytra installed you need a single of this 3 mods basically atm. The Forge End's Phantasm dev should be working soon on an End sinytra fix

**Comment by cal1407** [comment]
Thanks! looking forward to the fix

> Yeah we discussed it in intern with multiple devs, sinytra can only work with a single End mod at the time making UE, EP and EB cross-incompatible when Sinytra is used (so with sinytra installed you Can only play with a single of this 3 mods basically atm). The Forge End's Phantasm dev should be working soon on an End sinytra fix

**Comment by Nomandir** [comment]
I'm on 1.20.1 Forge 47.3.11, running Phantasm 0.4.1 and Unusual End 2.1.5. I don't have Sinytra installed (though I had previously installed/uninstalled it) and still experienced crash on startup with exit code 1. Can confirm the game can load with Unusual End without Phantasm.

**Comment by Sweetygamer2** [comment]
![image](https://github.com/user-attachments/assets/5907d0c4-7f95-4973-a783-bcbb3db2e93c)
The issue will be resolved on Unusual End's side for the Fabric + EP + UE combo in the next UE update, but clashs when the 3 mods are installed will still happen, this time the fault only being on EP/EB.

**Comment by SwanX1** [comment]
This is also an issue with Endless Biomes apparently.
See crash log from https://github.com/nekomaster1000/Resurvival-Housekeeping/issues/15:
```
[21:00:56] [pool-4-thread-1/WARN]: @Redirect conflict. Skipping phantasm.mixins.json:BiomeSourceMixin->@Redirect::getPhantasmPossibleBiomes(Ljava/util/function/Supplier;)Ljava/lang/Object; with priority 1000, already redirected by mixins.endlessbiomes.json:BiomeSourceMixin->@Redirect::getBiomes(Ljava/util/function/Supplier;)Ljava/lang/Object; with priority 1000
[21:00:56] [pool-4-thread-1/WARN]: @Redirect conflict. Skipping mixins.unusualend.json:BiomeSourceMixin->@Redirect::getBiomes(Ljava/util/function/Supplier;)Ljava/lang/Object; with priority 800, already redirected by mixins.endlessbiomes.json:BiomeSourceMixin->@Redirect::getBiomes(Ljava/util/function/Supplier;)Ljava/lang/Object; with priority 1000
```

**Comment by SashaKYotoz** [comment]
fixed in version 1.0 of EP
